### PR TITLE
Start some internazionalization and add some feature and spells

### PR DESCRIPTION
**Pull request by p4535992**
- Start some internazionalization with a helper class
- Compress the code on the class 'effect-definitons' (more easy to read)
- Add bug reporter on 'module.json'
- Added midi-qol like a module dependency on 'module.json'
- Added 'fortunes Favor' , 'rage path of the totem warriori', 'favoured Enemy' , 'greater favoured Enemy', 'almost Dead', 'wounded', 'unconscious'. 
- 
I will try in these day to make more internazionalization and management of the images.

### CODE REVIEW

**Comment by DFreds** [comment]
You probably shouldn't have close the other PR because now all of the other comments are lost. Conflicts can be resolved. But anyway, all of my previous comments still stand and need to be addressed.

**Comment by p4535992** [comment]
Hey Dfreds there is something wrong with this pull ? I dont' want to start writing more internazionalization until we agreed on the starting structure. Cheers.

**Comment by DFreds** [comment]
Please review the comments on #6. Just submitted them.

**Comment by p4535992** [comment]
Sorry for the inconvenience I did not think I would waste you so much time. I think it's okay now. If all is well this weekend I will try to complete internationalization. Cheers.

**Comment by DFreds** [comment]
I'm going to close this as it seems to have died down. Feel free to reopen if you get back to it

**Pull request closed without merging**
