### PR TITLE
Added Rage Bonus Damage and Token Magic Effect

### PR DESCRIPTION
**Pull request by Carlosjrlu**
Hello! I added the bonus damage to the Rage Effect, and also a token magic effect that my DM uses that seems cool.

### CODE REVIEW

**Comment by DFreds** [comment]
Rage damage is already handled via the dynamic-effects-adder.js. Where does this @scale stuff come from? Never seen it before.

**Comment by thatlonelybugbear** [comment]
It's from dnd5e 1.6.x onwards. Level advancement stuff

**Comment by Carlosjrlu** [comment]
Yeah, it's from the dnd5e system itself

**Comment by DFreds** [comment]
Nice, that's awesome. I think the parts about rage would need to removed from the dynamic effects adder before this got merged.

**Comment by DFreds** [comment]
@thatlonelybugbear @Carlosjrlu are there any other examples like this in the dnd system now? I don't know where this is documented and I was curious if I could do anything else

**Comment by thatlonelybugbear** [comment]
Bard's bardic inspiration , Rogue's sneak attack, Monks Martial Dice have scaled values for the SRD classes 
image

**Comment by DFreds** [comment]
Amazing! Thanks @thatlonelybugbear

**Pull request merged**
