### PR TITLE
An attempt to expand the module to a multisystem view (tentative 3) 

### PR DESCRIPTION
**Pull request by p4535992**
From a technical point of view, the idea is simply to create a class of "EffectDefinitions" for each system.

I started from the multisystem mechanism used by wasp for "item piles" and trying to touch as little code as possible.

### CODE REVIEW

**Comment by DFreds** [comment]
I think this is the right idea. I'll take a look. Did you have anything else you specifically were looking to add before I do? Because I'm also considering merging this to a separate branch and continuing my own work on top.

**Comment by p4535992** [comment]
Let's say I didn't go too far with my thinking because I didn't know if you would like the initial implementation. 

To tell you the truth as I wrote in a comment, I could not manage as I wanted the settings "DEFAULT_EFFECT_DEFINITIONS" in the initial hook , but at the moment I have no other functionality in mind .

Let me know if you have any suggestions or directions you would like me to make on this PR or if you prefer to take the charge right now.

**Comment by DFreds** [comment]
I think I'll take it over from here. Thank you!

Keeping this open for now

**Comment by DFreds** [comment]
The implementation can be tracked in branch all_systems

**Pull request closed without merging**
